# Workflow for linting and style checks
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::lintr
            any::styler
          needs: lint

      - name: Lint
        run: |
          lintr::lint_package()
        shell: Rscript {0}

      - name: Style check
        run: |
          if (!styler::style_pkg(dry = TRUE)) {
            message("Some files are not properly styled!")
            quit(status = 1)
          }
        shell: Rscript {0}
